# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: yarn build

    - uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'graveyard-keeper-bot-${{github.ref_name}}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.idea* /src* tsconfig* nodemon*'

    - uses: ncipollo/release-action@main
      with:
        artifacts: "graveyard-keeper-bot-*.zip"
        token: ${{ github.token }}
